Feature/parmoo
bandframework/bandframework pull request #58
Opened 2023-05-02 17:50 UTC by wildsm

This PR for the inclusion of ParMOO in the BAND.

Note that rather than being included as a submodule or have the source code in bandframework, the approach taken was to instead include sufficient documentation for the quick installation of ParMOO as well as how to obtain an example problem of ParMOO being run for a multi-objective calibration of (surrogate of) the Fayans energy density functional.

We are asking for reviewers to:

- follow the instructions in the README and confirm they are clear and complete
- examine the SDK compatibility document for correctness and completeness

Thank you!

2023-05-02 17:54 UTC, wildsm commented
Atting @thchang for awareness

2023-05-04 17:30 UTC, asemposki requested changes
Finished reviewing so far. Had one part of the README.md commands that might need to be changed, and one error importing the dash module which I do not appear to have. Should that be installed with parmoo in the requirements file?

2023-05-04 17:30 UTC, asemposki commented on software/parmoo/README.md
> +python3 parmoo_fayans_test.py --comms local --nworkers 4
I'm getting a 'ModuleNotFoundError: No module named 'dash'' error when I run this, from the file "C:\Users...\parmoo\viz\dashboard.py" file, at line 14: 'from dash import'. Do we need to install the dashboard package this is referencing first? That might be something to put in the REQUIREMENTS.txt file if so.

2023-05-04 21:02 UTC, mosesyhc commented on software/parmoo/README.md
> +git clone https://github.com/parmoo/parmoo-solver-farm/fayans-model-calibration-2022
Same behavior by @asemposki is observed.

Suggested changes:
After installing ParMOO, clone the [ParMOO Solver Farm] repository(https://github.com/parmoo/parmoo-solver-farm/):
```
git clone https://github.com/parmoo/parmoo-solver-farm.git
```
Within directory `parmoo-solver-farm/fayans-model-calibration-2022`, run the following ...

2023-05-04 21:08 UTC, mosesyhc commented on software/parmoo/README.md
> +python3 parmoo_fayans_test.py --comms local --nworkers 4
Both dash and kaleido packages are missing from the REQUIREMENTS.txt inside `fayan-model-calibration-2022` directory.  

Upon installing the two packages and rerunning the code, the expected results are returned.

The [REQUIREMENTS](https://github.com/parmoo/parmoo/blob/main/REQUIREMENTS) file under parmoo's main repository contains the necessary packages.  However, calling `pip install parmoo` does not install the two packages mentioned above.

2023-05-04 21:09 UTC, mosesyhc commented on software/parmoo/README.md
> +See the code in [`parmoo_fayans_test.py`](https://github.com/parmoo/parmoo-solver-farm/blob/main/fayans-model-calibration-2022/parmoo_fayans_test.py) for more details on how to preproduce these resul
Is it supposed to be "reproduce", instead of "preproduce"?

2023-05-04 21:30 UTC, mosesyhc commented on software/parmoo/parmoo-bandsdk.md
> +| 2. | Have a README file in the top directory that states a specific set of testing procedures for a user to verify the software was installed and run correctly. | Full| In addition to a README, Par
I tried to run `python3 setup.py test` after I have cloned and installed parmoo.  But I could not get it to run (I suspect this is because I am running from a Windows PowerShell).  

Console output:
```
Python version from setup.py is 3
'parmoo' is not recognized as an internal or external command,
operable program or batch file.
```

2023-05-04 21:31 UTC, mosesyhc requested changes
Reviewed parmoo in BAND.  

I have observed similar behavior about installation and package dependencies as @asemposki, added my observations in the comments, and suggested certain changes. See comments in README.md.

I included a comment for a minor typo.

I verified the BAND SDK compliance, except for one.  See comment under BAND SDK Mandatory Policy No.2.

2023-05-09 16:54 UTC, odell commented on software/parmoo/README.md
> +python3 parmoo_fayans_test.py --comms local --nworkers 4
I also had to install `kaleido` and `dash` before I could complete the test. Other than that, no issues.

2023-05-11 16:09 UTC, wildsm commented
Thanks @odell @mosesyhc @asemposki !
This has been updated by @thchang using [PR 59](https://github.com/bandframework/bandframework/pull/59).

In addition to clarifying the README, the corresponding REQUIREMENTS.txt file in the parmoo-solver-farm/fayans-model-calibration-2022 repository has been updated to better pull in dependencies.

2023-05-11 16:11 UTC, wildsm commented on software/parmoo/README.md
> +git clone https://github.com/parmoo/parmoo-solver-farm/fayans-model-calibration-2022
Addressed, thank you!

2023-05-11 16:11 UTC, wildsm commented on software/parmoo/README.md
> +python3 parmoo_fayans_test.py --comms local --nworkers 4
Addressed, thank you!

2023-05-11 16:13 UTC, wildsm commented on software/parmoo/parmoo-bandsdk.md
> +| 2. | Have a README file in the top directory that states a specific set of testing procedures for a user to verify the software was installed and run correctly. | Full| In addition to a README, Par
Correct, Windows is not currently supported, but with an appropriate bash executor you could also run the tests in Windows.

2023-05-11 16:14 UTC, wildsm commented on software/parmoo/README.md
> +See the code in [`parmoo_fayans_test.py`](https://github.com/parmoo/parmoo-solver-farm/blob/main/fayans-model-calibration-2022/parmoo_fayans_test.py) for more details on how to preproduce these resul
Yes! Changed.

2023-05-13 16:13 UTC, asemposki commented on software/parmoo/README.md
> +Running the above test produces a CSV file containing ParMOO's final database of design parameter and objective values in `fayans_test_results.csv` and saves a pairwise scatter plot of the Pareto fro
The plot structure looks the same as the one mentioned here that it should be similar to, but does not have the exact same scatter plot results. Is that to be expected?

2023-05-13 16:15 UTC, asemposki approved these changes
Made a note here about the difference in the plot I get vs the plot I'm expected to see. Not sure if they have to be the exact same. No code errors came up while running, and the REQUIREMENTS.txt file now contains all of the packages that I did not have previously installed, so everything looks good otherwise. 

If it is OK to have the plots not be the exact same result, then consider this approval of the inclusion of parmoo in BAND.

2023-05-15 16:09 UTC, wildsm commented on software/parmoo/README.md
> +Running the above test produces a CSV file containing ParMOO's final database of design parameter and objective values in `fayans_test_results.csv` and saves a pairwise scatter plot of the Pareto fro
Yes, this is as expected but we have added a note to reflect this. Thanks for raising the issue.

2023-05-15 16:53 UTC, mosesyhc approved these changes
The updates have fixed the previous issues.

2023-05-15 18:06 UTC, odell approved these changes

2023-05-30 23:51 UTC, merged

2023-05-30 23:51 UTC, wildsm commented
Thanks all